AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-notify

Globals:
  Function:
    Timeout: 3
    Tracing: Active     
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  NotifyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: NotifyAPI
      StageName: Prod
      Description: Notify API
      CorsConfiguration: 
        AllowMethods:  
          - POST
        AllowHeaders: 
          - '*'
        AllowOrigins: 
          - '*'
  
  SNSNotifyTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: NotifyTopic
      TopicName: NotifyTopic

  NotifyValidationFunction:
    Type: AWS::Serverless::Function  
    Properties:    
      CodeUri: notify-validation/
      Handler: app.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Policies: 
        - SNSPublishMessagePolicy:
            TopicName: !Ref SNSNotifyTopic
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref NotifyApi
            Path: /hello
            Method: get
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
