AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-notify

Globals:
  Function:
    Timeout: 3
    Tracing: Active     
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
Resources:
  NotifyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: NotifyAPI
      StageName: Prod
      Description: Notify API
      CorsConfiguration: 
        AllowMethods:  
          - POST
        AllowHeaders: 
          - '*'
        AllowOrigins: 
          - '*'
  
  SNSNotifyTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: NotifyTopic
      TopicName: NotifyTopic
  
  SNSNotifyHighPrioritySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSNotifyTopic
      Endpoint: !GetAtt SQSNotifyHighPriorityQueue.Arn
      FilterPolicy: 
        priority: 
          - HIGH
  
  SNSNotifyMediumPrioritySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSNotifyTopic
      Endpoint: !GetAtt SQSNotifyMediumPriorityQueue.Arn
      FilterPolicy: 
        priority: 
          - MEDIUM
  
  SNSNotifyLowPrioritySubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref SNSNotifyTopic
      Endpoint: !GetAtt SQSNotifyLowPriorityQueue.Arn
      FilterPolicy: 
        priority: 
          - LOW 
  
  SQSNotifyHighPriorityQueue:
    Type: AWS::SQS::Queue
    Properties:     
      QueueName: NotifyHighPriorityQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600
  
  SQSNotifyHighPriorityQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSNotifyHighPriorityQueue 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: SQS:SendMessage
            Resource: !GetAtt SQSNotifyHighPriorityQueue.Arn 
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSNotifyTopic

  SQSNotifyMediumPriorityQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSNotifyMediumPriorityQueue 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: SQS:SendMessage
            Resource: !GetAtt SQSNotifyMediumPriorityQueue.Arn 
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSNotifyTopic
  
  SQSNotifyLowPriorityQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref SQSNotifyLowPriorityQueue 
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: SQS:SendMessage
            Resource: !GetAtt SQSNotifyLowPriorityQueue.Arn 
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref SNSNotifyTopic
             
  
  SQSNotifyMediumPriorityQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotifyMediumPriorityQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600

  SQSNotifyLowPriorityQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: NotifyLowPriorityQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 345600

  NotifyProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: NotifyProcessFunction
      CodeUri: notify-process/
      Handler: app.handler  
      Runtime: nodejs20.x
      MemorySize: 128
      Policies: 
        - SQSPollerPolicy:
            QueueName: !Ref SQSNotifyHighPriorityQueue
        - SQSPollerPolicy:
            QueueName: !Ref SQSNotifyMediumPriorityQueue
        - SQSPollerPolicy:
            QueueName: !Ref SQSNotifyLowPriorityQueue
      Architectures:
        - x86_64
      Events:
        SQSNotifyHighPriorityQueueEvent:
          Type: SQS 
          Properties:
            Queue: !GetAtt SQSNotifyHighPriorityQueue.Arn
            BatchSize: 10
        SQSNotifyMediumPriorityQueueEvent:
          Type: SQS 
          Properties:
            Queue: !GetAtt SQSNotifyMediumPriorityQueue.Arn
            BatchSize: 10
        SQSNotifyLowPriorityQueueEvent:
          Type: SQS 
          Properties:
            Queue: !GetAtt SQSNotifyLowPriorityQueue.Arn
            BatchSize: 10

  NotifyValidationFunction:
    Type: AWS::Serverless::Function  
    Properties:    
      FunctionName: NotifyValidationFunction
      CodeUri: notify-validation/
      Handler: app.handler
      Runtime: nodejs20.x
      MemorySize: 128
      Policies: 
        - SNSPublishMessagePolicy:
            TopicName: !Ref SNSNotifyTopic
      Architectures:
      - x86_64
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref  SNSNotifyTopic
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref NotifyApi
            Path: /notification
            Method: post
    Metadata: 
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts
